import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { parse } from 'yaml';
import { buildAnalysisPackage, formatClassificationLabels, writeAnalysisPackage } from './import-korean-market-analysis.mjs';

function fixture(){return {content_type:'foreign_flow',publication_date:'2026-09-19',as_of:'2026-09-18 장 마감',title:'외국인 순매수 분석',subtitle:'원자료로 확인한 수급 분석',executive_summary:'순매수 규모와 시가총액을 함께 비교했습니다.',selection_criteria:['KRX 코스피 보통주','직전 완료 거래일'],calculation_method:['순매수 금액을 시가총액과 함께 비교'],analysis_limitations:['수급은 매수 주체의 목적을 직접 설명하지 않습니다.'],stocks:[{rank:1,name:'검증기업',ticker:'000001',primary_metric:'100억원',reason:'KRX 집계에서 확인한 순매수 상위 종목입니다.',evidence:'거래소 집계와 공시를 교차 확인했습니다.',value_view:'수급과 실적을 분리해 봅니다.',outlook:'후속 수급과 실적 공시를 확인합니다.',risks:['단기 수급 반전']}],synthesis:{classification:'종목 선택형 매수',analysis:'업종 전체보다 개별 종목의 비중이 높았습니다.',watch_items:['다음 거래일 수급']},sources:[{title:'공식 원자료',url:'https://example.com/source',accessed:'2026-09-19'}]};}

test('builds a published analysis with methods and limitations',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-'));await writeFile(path.join(root,'article.json'),JSON.stringify(fixture()));const result=await buildAnalysisPackage(root,{publish:true});assert.equal(result.slug,'2026-09-19-foreign-flow');assert.equal(result.frontmatter.analysisKind,'foreign-flow');assert.equal(result.frontmatter.draft,false);assert.match(result.body,/분석 대상 비교/);});
test('fails closed without methodology',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-'));const value=fixture();delete value.calculation_method;await writeFile(path.join(root,'article.json'),JSON.stringify(value));await assert.rejects(()=>buildAnalysisPackage(root),/계산 방법/);});
test('writes the analysis collection file',async()=>{const pkg=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-pkg-'));const site=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-site-'));await mkdir(path.join(site,'src/content/analyses'),{recursive:true});await writeFile(path.join(pkg,'article.json'),JSON.stringify(fixture()));const result=await writeAnalysisPackage(pkg,site,{publish:true});assert.match(result.contentFile,/src\/content\/analyses/);});
test('serializes one-stock ISO-dated research for the Astro collection schema',async()=>{const pkg=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-pkg-'));const site=await mkdtemp(path.join(os.tmpdir(),'caelus-analysis-site-'));await mkdir(path.join(site,'src/content/analyses'),{recursive:true});const value=fixture();value.content_type='weekend_research';value.publication_date='2026-09-20';value.as_of='2026-09-20T11:50:34+09:00';await writeFile(path.join(pkg,'article.json'),JSON.stringify(value));const result=await writeAnalysisPackage(pkg,site,{publish:true});const markdown=await readFile(result.contentFile,'utf8');const frontmatter=parse(markdown.split('---')[1]);assert.equal(result.slug,'2026-09-20-weekly-research');assert.equal(typeof frontmatter.asOf,'string');assert.equal(frontmatter.asOf,value.as_of);assert.ok(frontmatter.highlights.length>=2);assert.match(frontmatter.highlights[1],/^분석 분류 — /);});

test('starts every classification label after a blank line and styles only the label',()=>{const labels=['기본 시나리오','상방 시나리오','하방 시나리오','추적 지표','종합 해석','기업·산업 배경','가치 판단'];const input=labels.map(label=>`[${label}] 내용`).join(' ');const rendered=formatClassificationLabels(input);for(const label of labels)assert.match(rendered,new RegExp(`(?:^|\\n\\n)<strong class="analysis-classification-label">\\[${label}\\]<\/strong> 내용`));assert.doesNotMatch(rendered,/<strong class="analysis-classification-label">[^<]*내용/);});
test('formats classification labels for every Korean-market analysis kind',async()=>{for(const contentType of ['foreign_flow','intraday_gainers','weekend_research']){const root=await mkdtemp(path.join(os.tmpdir(),'caelus-labels-'));const value=fixture();value.content_type=contentType;value.stocks[0].evidence='앞 문장. [기업·산업 배경] 배경 내용. [가치 판단] 판단 내용.';value.stocks[0].outlook='[기본 시나리오] 기본 내용. [상방 시나리오] 상방 내용. [하방 시나리오] 하방 내용. [추적 지표] 지표 내용. [종합 해석] 해석 내용.';await writeFile(path.join(root,'article.json'),JSON.stringify(value));const result=await buildAnalysisPackage(root);assert.equal((result.body.match(/class="analysis-classification-label"/g)||[]).length,7);assert.match(result.body,/앞 문장\.\n\n<strong class="analysis-classification-label">\[기업·산업 배경\]<\/strong> 배경 내용\./);}});
