import {readdir,readFile} from 'node:fs/promises';import path from 'node:path';import {parse} from 'yaml';
const root=process.cwd(),contentRoot=path.join(root,'src','content'),errors=[];const categories=new Set(['market-signals','global-investing','etf-structure','company-analysis']);
async function files(dir){const entries=await readdir(dir,{withFileTypes:true});return (await Promise.all(entries.map(e=>e.isDirectory()?files(path.join(dir,e.name)):path.join(dir,e.name)))).flat().filter(f=>f.endsWith('.md'));}
function document(file,source){const m=source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);if(!m){errors.push(`${file}: frontmatter 누락`);return null}try{return{data:parse(m[1]),body:m[2],source,file}}catch(e){errors.push(`${file}: YAML 오류 ${e.message}`);return null}}
async function load(name){const out=[];for(const f of await files(path.join(contentRoot,name))){const s=await readFile(f,'utf8'),d=document(path.relative(root,f),s);if(d)out.push(d)}return out}
const guides=await load('guides'),briefings=await load('briefings');const publicGuides=guides.filter(d=>d.data.draft===false),publicBriefings=briefings.filter(d=>d.data.draft===false);if(publicGuides.length<12)errors.push(`공개 가이드는 최소 12개여야 합니다: ${publicGuides.length}`);if(publicBriefings.length<12)errors.push(`공개 브리핑은 최소 12개여야 합니다: ${publicBriefings.length}`);
const todayKst=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
for(const [kind,docs] of [['guides',guides],['briefings',briefings]]){const slugs=new Set();for(const d of docs){const x=d.data;if(!x.title||!x.description||!x.slug||!x.summary)errors.push(`${d.file}: 필수 텍스트 누락`);if(slugs.has(x.slug))errors.push(`${d.file}: slug 중복`);slugs.add(x.slug);if(x.author!=='카일루스')errors.push(`${d.file}: 작성자 불일치`);const published=typeof x.publishedAt==='string'?x.publishedAt.slice(0,10):x.publishedAt instanceof Date?x.publishedAt.toISOString().slice(0,10):'';if(x.draft===false&&(x.editorialApproved!==true||!published||published>todayKst))errors.push(`${d.file}: 공개·승인·발행일 상태 오류`);if(!Array.isArray(x.sources)||x.sources.length<1)errors.push(`${d.file}: 출처 누락`);const bodyChars=d.body.trim().length;if(bodyChars<1200)errors.push(`${d.file}: 본문이 지나치게 짧음(${bodyChars})`);if(x.contentTier==='flagship'){const [min,max]=kind==='guides'?[2500,4000]:[1800,3500];if(bodyChars<min||bodyChars>max)errors.push(`${d.file}: flagship 본문 분량 오류(${bodyChars}, 기준 ${min}~${max})`);if(!Array.isArray(x.cards)||x.cards.length!==8)errors.push(`${d.file}: flagship 카드가 8장이 아님`);}for(const card of x.cards||[]){if(!/^\/content\/(briefings|guides)\/[a-z0-9-]+\/slide-\d{2}\.png$/.test(card.image||''))errors.push(`${d.file}: 카드 이미지 경로 오류`);if(String(card.description||'').length<40)errors.push(`${d.file}: 카드 설명이 지나치게 짧음`);if(String(card.alt||'').length<15||String(card.alt||'').length>120)errors.push(`${d.file}: 카드 대체 텍스트 길이 오류`);}for(const s of x.sources||[]){try{const u=new URL(s.url);if(u.protocol!=='https:')throw 0}catch{errors.push(`${d.file}: 출처 URL 오류 ${s.url}`)}}if(kind==='guides'&&!categories.has(x.category))errors.push(`${d.file}: 카테고리 오류`);if(kind==='briefings'){const date=String(x.briefingDate).slice(0,10);if(x.slug!==date)errors.push(`${d.file}: slug와 briefingDate 불일치`);const [y,m,day]=date.split('-').map(Number);if(!x.title.startsWith(`${y}년 ${m}월 ${day}일`))errors.push(`${d.file}: 제목 날짜 불일치`);if(/\[(IMAGE|CHART):|\[(CL|L)-?\d+\]/i.test(d.source))errors.push(`${d.file}: 내부 제작 표식 노출`);}}
}
const forbidden=[/(?<!\d)01[016789][-\.\s]\d{3,4}[-\.\s]\d{4}(?!\d)/,/(?:경기도|서울특별시|부산광역시)\s+[^\n]{1,50}(?:로|길)\s*\d+/];for(const d of [...guides,...briefings])for(const p of forbidden)if(p.test(d.source))errors.push(`${d.file}: 공개 금지 개인정보`);
if(errors.length){console.error(`콘텐츠 검증 실패 (${errors.length}건)`);errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log(`콘텐츠 검증 완료: 가이드 ${guides.length}개, 브리핑 ${briefings.length}개`);
